"[#] doc":
 - 'doc/*'
 - 'doc/**/*'
 - 'examples/**/*'

"[#] maplike":
 - 'maplike/*'
 - 'maplike/**/*'

"[#] optics":
 - 'optics/*'
 - 'optics/**/*'

"[#] pipe":
 - 'pipe/*'
 - 'pipe/**/*'

"[#] pure":
 - 'pure/*'
 - 'pure/**/*'

"[#] seq":
 - 'seq/*'
 - 'seq/**/*'
