"[#] doc":
 - doc/*
 - doc/**/*
 - examples/**/*

"[#] pure":
 - pure/*
 - pure/**/*

"[#] maplike":
 - maplike/*
 - maplike/**/*

"[#] optics":
 - optics/*
 - optics/**/*

"[#] seq":
 - seq/*
 - seq/**/*
