name: check
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  golangci-lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - uses: actions/checkout@v3

      - uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: latest
          args: --verbose

  check:
    runs-on: ubuntu-latest
    steps:

      - name: golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: checkout
        uses: actions/checkout@v2
 
      # - name: go get tools
      #   run: |
      #     go get golang.org/x/lint/golint
    
      - name: go build
        run: |
          go build ./...
    
      - name: go vet
        run: |
          go vet ./...
  
      # - name: golint
      #   run: |
      #     golint ./...

      - name: go test
        run: |
          go test -v -coverprofile=profile.cov ./...

      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
